import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '@/layout';
import Dashboard from '../components/dashboard';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className="flex-shrink-0 p-5 mt-[72px]">
                    <Dashboard />
                </main>
            </Layout>
        </>
    );
}
